### ISSUE TITLE
[FEATURE] : sauvegarde de l'utilisateur connecte

### ISSUE THREAD

**Issue by ahmet40** [BOURREAUQuentin/SAE-Web-PhP#10]
cette issue va nous permettre de savoir sur toutes les pages qui est l'utilisateur connecter.

**Comment by BOURREAUQuentin** [comment]
pour l'instant, j'ai fait la sauvegarde de l'utilisateur connecté et pour tester j'ai ajouté un bouton login/logout suivant si on est connecté et s'inscrire dans la page connexion. J'ai fait l'affichage des playlists de l'utilisateur sur page principale. J'ai fait l'ajout d'une musique à une playlist (quand elle y est déjà dedans ca renvoie pas de bug mais j'arrive pas à afficher l'erreur à l'utilisateur)

**Comment by BOURREAUQuentin** [comment]
je reglerai le probleme de l'image d'une playlist prochainement
