### ISSUE TITLE
[FEATURE] : Ajouter musique

### ISSUE THREAD

**Issue by MaverickPrevost** [BOURREAUQuentin/SAE-Web-PhP#46]

**Comment by BOURREAUQuentin** [comment]
j'ai ajouté un lecteur de musique dans la page album.php. on peut lire le son, passer à la musique suivante ou précédente de l'album et relancer le son actuel, régler le volume du son et on voit également la file d'attente des sons de l'album. pour l'instant je n'ai ajouté que 2 albums complets fonctionnels car les sons prennent trop de places
