### ISSUE TITLE
[FEATURE] : Faire les genres dans la partie admin

### ISSUE THREAD

**Issue by MaverickPrevost** [BOURREAUQuentin/SAE-Web-PhP#48]

**Comment by BOURREAUQuentin** [comment]
j'ai fait la page admin_genre pour ajouter un genre + possibilité d'ajouter plusieurs genres à un nouvel album + ajout durée_son_musique suivant fichier mp3 chargé dans admin_musique + refactoring dossiers images + update mcd. désolé j'ai fait beaucoup de correctifs dans cette branche.
