### ISSUE TITLE
[FIX] : correction et ajout diverses

### ISSUE THREAD

**Issue by MaverickPrevost** [BOURREAUQuentin/SAE-Web-PhP#87]
- Supprimer l'image quand on supprime artiste, album, playlist
- Recherche avec plusieurs critères
- Message d'erreur pour les images trop grandes
- Factorisation fichiers js
- Ajouter background image 
- Gérer nombres de streams

**Comment by BOURREAUQuentin** [comment]
j'ai fait : 
   - Supprimer l'image quand on supprime artiste, album, playlist
   - Recherche avec plusieurs critères (genre et année)
   - Message d'erreur pour les images trop grandes (pas besoin car y'a pas de limites)
   - Factorisation fichiers js (systeme de likes, il manquera à la limite si on a le temps la moyenne d'un album et notes)
   - Ajouter background image (page d'un artiste)
   - Gérer nombres de streams (page album, playlist et titres_likes quand on écoute une nouvelle musique)
